### ISSUE TITLE
🐛 FIX. 각종 오류 해결

### ISSUE THREAD

**Issue by junhaa** [MemorAIzee/MemorAIzee-BackEnd#63]
# 📝 Preview

🐛 FIX. 각종 오류 해결

# ✅ Todo
- [x] 검색 조회시 사용자 이미지가 전달되지 않는 오류
- [x] Place 가 중복되어 저장되는 오류
- [x] 장소 상세정보 이미지 url 전달

# 📌 Remark
