### ISSUE TITLE
✨ FEAT. 앨범 API 구현

### ISSUE THREAD

**Issue by jinhahakim** [MemorAIzee/MemorAIzee-BackEnd#8]
# 📝 Preview

앨범 기능 구현에 대한 Todo list

# ✅ Todo
- [x] Google Map API 사용
- [x] Design AI 알아보기
- [x] 앨범 CRUD 기능 구현하기

# 📌 Remark

**Comment by jinhahakim** [comment]
앨범 기능
